import React from "react"
import type { Metadata } from "next"
import 'leaflet/dist/leaflet.css'
import '@/styles/main.scss'
import Header from '@/components/Header'
import Footer from "@/components/Footer";


export const metadata: Metadata = {
  title: "Baklen Method",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru" data-scroll-behavior="smooth">
      <body>
      <Header />
        {children}
      <Footer />
      </body>
    </html>
  );
}
